version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file:
      - .env

    networks:
      - my_inception
    restart: always
    volumes:
      - mariadbVolume:/var/lib/mysql
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - my_inception
    env_file:
      - .env
    restart: always
    volumes:
      - wpVolume:/var/www/html
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - my_inception
    restart: always
    volumes:
      - wpVolume:/var/www/html

networks:
  my_inception:
    driver: bridge

volumes:
  mariadbVolume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ebakchic/data/mariadb
  wpVolume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ebakchic/data/wordpress
